// pipeline {
//     agent any

//     options {
//         timeout(time: 30, unit: 'MINUTES')
//         timestamps()
//     }

//     stages {
//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }

//         stage('Install & Lint & Build') {
//             agent {
//                 docker {
//                     image 'node:22-alpine'
//                     reuseNode true
//                 }
//             }
//             steps {
//                 sh 'node -v && npm -v'
//                 sh 'npm ci'
//                 sh 'npm run lint'
//                 sh 'npm run build'
//             }
//         }
//     }

//     post {
//         success {
//             archiveArtifacts artifacts: 'dist/**/*', fingerprint: true, allowEmptyArchive: false
//         }
//         failure {
//             echo 'Pipeline thất bại - xem log từng stage (Install & Lint & Build).'
//         }
//     }

// }

// // docker compose build --no-cache
// // docker compose up -d
// // docker compose exec jenkins docker version


pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install & Lint & Build') {
            steps {
                // Chui vào đúng thư mục chứa package.json
                dir('lab21/jenkins-app') {
                    // Đổi 'bat' thành 'sh' vì Jenkins đang chạy trên Linux
                    sh 'node -v && npm -v'
                    sh 'npm install'
                    sh 'npm run lint'
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'lab21/jenkins-app/dist/**/*', fingerprint: true, allowEmptyArchive: false
        }
        failure {
            echo 'Pipeline thất bại - xem log từng stage (Install & Lint & Build).'
        }
    }
}