// pipeline {
//     agent any

//     options {
//         timeout(time: 30, unit: 'MINUTES')
//         timestamps()
//     }

//     stages {
//         stage('Checkout') {
//             steps {
//                 checkout scm
//             }
//         }

//         stage('Install & Lint & Build') {
//             agent {
//                 docker {
//                     image 'node:22-alpine'
//                     reuseNode true
//                 }
//             }
//             steps {
//                 sh 'node -v && npm -v'
//                 sh 'npm ci'
//                 sh 'npm run lint'
//                 sh 'npm run build'
//             }
//         }
//     }

//     post {
//         success {
//             archiveArtifacts artifacts: 'dist/**/*', fingerprint: true, allowEmptyArchive: false
//         }
//         failure {
//             echo 'Pipeline thất bại - xem log từng stage (Install & Lint & Build).'
//         }
//     }

// }

// // docker compose build --no-cache
// // docker compose up -d
// // docker compose exec jenkins docker version


pipeline {
    agent any // Jenkins chính (máy chủ) vẫn chạy

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {
        stage('Install & Build') {
            agent {
                docker {
                    // Jenkins sẽ tự tải image này về để có môi trường Node.js
                    image 'node:22-alpine'
                    // Giữ lại các file đã checkout từ stage trước
                    reuseNode true 
                }
            }
            steps {
                dir('lab21/jenkins-app') {
                    sh 'node -v'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'lab21/jenkins-app/dist/**/*', fingerprint: true, allowEmptyArchive: false
        }
        failure {
            echo 'Pipeline thất bại - Kiểm tra lại Docker hoặc Node.js'
        }
    }
}